# Generated by Django 5.2 on 2025-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='soccerboot',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
