# Generated by Django 5.2 on 2025-04-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_display_name_alter_soccerboot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerboot',
            name='oders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boots', to='api.order'),
        ),
    ]
