# Generated by Django 5.2 on 2025-04-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
